# Generated by Django 4.0.2 on 2022-02-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('element', models.CharField(max_length=50)),
                ('conselation', models.CharField(max_length=50)),
                ('havetodo', models.CharField(max_length=50)),
                ('completed', models.BooleanField()),
            ],
        ),
    ]
